spring:
  jmx:
    enabled: true

  application:
    name: scm

  datasource:
    url: jdbc:mysql://localhost:3306/scm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Thakur@7

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-name: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

server:
  port: 8081
