spring:
  jmx:
    enabled: true

  application:
    name: scm

  datasource:
    url: jdbc:mysql://localhost:3306/scm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Thakur@7

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 385859815128-lj3o9tk8rn41hk58o9p13bjagl160t0f.apps.googleusercontent.com
            client-secret: //secret
            scope:
              - email
              - profile

server:
  port: 8081
